[package]
name = "words-lookup-bot"
version = "0.13.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.7"
chrono = "0.4.41"
futures = "0.3.31"
log = "0.4.29"
serde = "1.0.228"
regex = "1.12.2"
shuttle-runtime = "0.57.0"
string-builder = "0.2.0"
urlencoding = "2.1.3"

[dependencies.teloxide]
version = "0.17.0"
features = ["macros"]

[dependencies.reqwest]
version = "0.12.25"
features = ["json"]

[dependencies.tokio]
version = "1.48"
features = ["rt-multi-thread", "macros"]
