[package]
name = "words-lookup-bot"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
reqwest = { version = "0.12.7", features = ["json"] }
serde = "1.0.197"
shuttle-runtime = "0.56.0"
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
log = "0.4.27"
string-builder = "0.2.0"
futures = "0.3.31"
