[package]
name = "words-lookup-bot"
version = "0.12.2"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
axum = "0.8.7"
chrono = "0.4.41"
futures = "0.3.31"
log = "0.4.27"
serde = "1.0.197"
regex = "1.11.1"
shuttle-runtime = "0.57.0"
string-builder = "0.2.0"
urlencoding = "2.1.3"

[dependencies.teloxide]
version = "0.17.0"
features = ["macros"]

[dependencies.reqwest]
version = "0.12.7"
features = ["json"]

[dependencies.tokio]
version = "1.8"
features = ["rt-multi-thread", "macros"]
