[package]
name = "words-lookup-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
reqwest = { version = "0.12.7", features = ["json"] }
log = "0.4"
serde = "1.0.197"
shuttle-runtime = "0.56.0"
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
