name: warm_up.yml
on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  warm_up:
    runs-on: ubuntu-latest
    steps:
      - name: Do it
        run: |
          curl --fail --show-error --silent \
            --max-time 15 --retry 3 --retry-delay 2 \
            -X GET https://words-lookup-bot-st7l.shuttle.app/warm_up